apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: database
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30037
  selector:
    app: redis
